# Generated by Django 2.2.6 on 2025-05-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20250527_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='тут был пост без текста'),
            preserve_default=False,
        ),
    ]
